-
  name: getvoip_varnish_1
  host: ${EXPOSE_HOST}
-
  name: getvoip_node_1
  host: node.${EXPOSE_HOST}
-
  name: getvoip_health_1
  host: health.${EXPOSE_HOST}
-
  name: getvoip_recorder_1
  host: sessions.${EXPOSE_HOST}
-
  name: getvoip_elastic_1
  host: elastic.${EXPOSE_HOST}
-
  name: getvoip_kibana_1
  host: kibana.${EXPOSE_HOST}
  port: 5601
-
  name: getvoip_grafana_1
  host: grafana.${EXPOSE_HOST}